### ISSUE TITLE
Meta-issue with improvements for next version

### ISSUE THREAD

**Issue by sethaxen** [sethaxen/rand_invwishart#2]
- [ ] The standard algorithm from Jones can be improved for $\Omega$ and $U_\Omega$ parameterizations by using the standard algorithm to draw $C \sim \mathrm{chol}\mathcal{W}^{-1}_m(n, I_m)$ and multiply by $U_\Omega$ instead of constructing $U_\Sigma$.
    - For `retchol=false`, this removes one triangular inverse, while for `retchol=true`, it removes a triangular inverse, a triangular product, and a Cholesky decomposition
- [ ] We should note that our algorithm can use `trsm` in place of a `trmm` and `trtri` for greater accuracy and slightly more speed when $U_\Omega$ can be overwritten.
    - Probably needs a refactor of `cholesky_upper` and to explicitly declare storage in algorithms
- [ ] explicitly mention reference implementations are in the Julia language
- [ ] add benchmarks? op counting is sufficient to determine which algorithm is most efficient in this case, but maybe someone wants to know how much faster it is practically. This is highly implementation-specific though, so only worthwhile doing if we eliminate all overhead, i.e. preallocate all storage and make sure that we effectively are just calling BLAS and LAPACK subroutines.

Misc:
- [ ] improve CI. pretty sure I hastily implemented the Bonferroni correction wrong.
